service: conventional-mergebot

plugins:
  - serverless-offline

provider:
  name: aws
  logRetentionInDays: 1
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  # Set to maximum timeout for API Gateway functions
  timeout: 30
  memorySize: ${file(config/config.${self:provider.stage}.json):memorySize}

functions:
  probot:
    handler: handler.probot

    environment:
      WEBHOOK_SECRET: ${file(config/config.${self:provider.stage}.json):WEBHOOK_SECRET}
      APP_ID: ${file(config/config.${self:provider.stage}.json):APP_ID}
      PRIVATE_KEY_PATH: keys/private-key.${self:provider.stage}.pem
      AUTOMERGE_BRANCHES: ${file(config/config.${self:provider.stage}.json):AUTOMERGE_BRANCHES}
      CONFIG: ${file(config/config.${self:provider.stage}.json):CONFIG}
      MAIN_BRANCH: ${file(config/config.${self:provider.stage}.json):MAIN_BRANCH}
    events:
      - http:
          path: /
          method: post
