service: conventional-mergebot

plugins:
  - serverless-offline

provider:
  name: aws
  logRetentionInDays: 1
  profile: serverless
  runtime: nodejs8.10
  stackTags:
    Business Unit: COM
  stage: ${opt:stage, 'dev'}
  timeout: 120

functions:
  probot:
    handler: handler.probot

    environment:
      WEBHOOK_SECRET: ${file(config/config.${self:provider.stage}.json):WEBHOOK_SECRET}
      APP_ID: ${file(config/config.${self:provider.stage}.json):APP_ID}
      PRIVATE_KEY_PATH: keys/private-key.${self:provider.stage}.pem
      REVIEW_TEAMS_RULES: ${file(config/config.${self:provider.stage}.json):REVIEW_TEAMS_RULES}
    events:
      - http:
         path: /
         method: post
